// Defined in Codex Master Data Sheet
// Refer: https://docs.google.com/spreadsheets/d/1hXUeCZgIUyx_liykNu6tlDJVwPu7MLKu_TIOoBwvdTo/edit#gid=79351264

import { CodeillusionPackageCircleDefinition } from '../../../../domain/entities/codex/CodeillusionPackageDefinition'

export const codeillusionPackageCircleDefinitionsMapByChapterId: (staticFilesBaseUrl: string) => Record<string, CodeillusionPackageCircleDefinition[]> = (staticFilesBaseUrl) => {
  const asStaticFileUrl = (path: string) => new URL(path, staticFilesBaseUrl).toString()
  return {
    'chapter-codeillusion-1': [
      {
        id: 'circle-codeillusion-basic-principal-basic',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-1',
        course: 'basic',
        bookName: "The Principal's Test",
        bookImageUrl: asStaticFileUrl('/images/b_principal_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_principal_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_principal_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-mickey-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-1',
        course: 'mediaArt',
        bookName: 'Circle Art',
        bookImageUrl: asStaticFileUrl('/images/b_mickey_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_mickey_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_mickey_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-donald-web_design',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-1',
        course: 'webDesign',
        bookName: "The Hat Shop's Website",
        bookImageUrl: asStaticFileUrl('/images/b_donald_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_donald_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_donald_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-goofy-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-1',
        course: 'gameDevelopment',
        bookName: 'Sound Machine',
        bookImageUrl: asStaticFileUrl('/images/b_goofy_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_goofy_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_goofy_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-2': [
      {
        id: 'circle-codeillusion-basic-aladdin-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-2',
        course: 'gameDevelopment',
        bookName: 'Flying Carpet',
        bookImageUrl: asStaticFileUrl('/images/b_aladdin_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_aladdin_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_aladdin_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-tangled-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-2',
        course: 'mediaArt',
        bookName: 'Sky Lanterns',
        bookImageUrl: asStaticFileUrl('/images/b_tangled_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_tangled_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_tangled_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-zootopia-web_design',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-2',
        course: 'webDesign',
        bookName: 'Person Finder Site',
        bookImageUrl: asStaticFileUrl('/images/b_zootopia_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_zootopia_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_zootopia_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-3': [
      {
        id: 'circle-codeillusion-basic-sugar1-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-3',
        course: 'gameDevelopment',
        bookName: 'Dungeon Escape',
        bookImageUrl: asStaticFileUrl('/images/b_sugar1_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sugar1_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sugar1_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-beauty-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-3',
        course: 'mediaArt',
        bookName: 'Mirror Magic',
        bookImageUrl: asStaticFileUrl('/images/b_beauty_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_beauty_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_beauty_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-4': [
      {
        id: 'circle-codeillusion-basic-mermaid-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-4',
        course: 'mediaArt',
        bookName: 'School of Fish',
        bookImageUrl: asStaticFileUrl('/images/b_mermaid_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_mermaid_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_mermaid_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-stitch-web_design',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-4',
        course: 'webDesign',
        bookName: 'Photo Gallery',
        bookImageUrl: asStaticFileUrl('/images/b_stitch_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_stitch_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_stitch_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-alice-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-4',
        course: 'gameDevelopment',
        bookName: "Queen's Card",
        bookImageUrl: asStaticFileUrl('/images/b_alice_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_alice_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_alice_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-5': [
      {
        id: 'circle-codeillusion-basic-pooh-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-5',
        course: 'gameDevelopment',
        bookName: 'Honey Hunt',
        bookImageUrl: asStaticFileUrl('/images/b_pooh_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_pooh_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_pooh_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-bighero6-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-5',
        course: 'gameDevelopment',
        bookName: 'Breaking Tiles',
        bookImageUrl: asStaticFileUrl('/images/b_bighero6_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_bighero6_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_bighero6_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-6': [
      {
        id: 'circle-codeillusion-basic-snowwhite-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-6',
        course: 'gameDevelopment',
        bookName: 'Jewel Puzzle',
        bookImageUrl: asStaticFileUrl('/images/b_snowwhite_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_snowwhite_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_snowwhite_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-sugar2-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-6',
        course: 'gameDevelopment',
        bookName: 'Wreck-It Ralph',
        bookImageUrl: asStaticFileUrl('/images/b_sugar2_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sugar2_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sugar2_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-7': [
      {
        id: 'circle-codeillusion-basic-frozen-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-7',
        course: 'mediaArt',
        bookName: 'Snow Magic',
        bookImageUrl: asStaticFileUrl('/images/b_frozen_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_frozen_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_frozen_character1_completed.png'),
      },
      {
        id: 'circle-codeillusion-basic-sleepingbeauty-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-7',
        course: 'gameDevelopment',
        bookName: 'Dragon & Sword',
        bookImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_book.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_character1.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_character1_completed.png'),
      },
    ],
    'chapter-codeillusion-8': [
      {
        id: 'circle-codeillusion-advanced-tangled-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-8',
        course: 'mediaArt',
        bookName: 'Fireworks Magic',
        bookImageUrl: asStaticFileUrl('/images/b_tangled_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_tangled_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_tangled_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-aladdin-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-8',
        course: 'gameDevelopment',
        bookName: 'Flying Carpet',
        bookImageUrl: asStaticFileUrl('/images/b_aladdin_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_aladdin_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_aladdin_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-alice-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-8',
        course: 'gameDevelopment',
        bookName: "Queen's Card",
        bookImageUrl: asStaticFileUrl('/images/b_alice_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_alice_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_alice_character2_completed.png'),
      },
    ],
    'chapter-codeillusion-9': [
      {
        id: 'circle-codeillusion-advanced-mermaid-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-9',
        course: 'mediaArt',
        bookName: 'School of Fish',
        bookImageUrl: asStaticFileUrl('/images/b_mermaid_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_mermaid_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_mermaid_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-stitch-web_design',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-9',
        course: 'webDesign',
        bookName: 'Photo Gallery',
        bookImageUrl: asStaticFileUrl('/images/b_stitch_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_stitch_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_stitch_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-pooh-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-9',
        course: 'gameDevelopment',
        bookName: 'Hunny Hunt',
        bookImageUrl: asStaticFileUrl('/images/b_pooh_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_pooh_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_pooh_character2_completed.png'),
      },
    ],
    'chapter-codeillusion-10': [
      {
        id: 'circle-codeillusion-advanced-beauty-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-10',
        course: 'mediaArt',
        bookName: 'Mirror Magic',
        bookImageUrl: asStaticFileUrl('/images/b_beauty_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_beauty_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_beauty_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-zootopia-web_design',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-10',
        course: 'webDesign',
        bookName: 'Zootopia Police',
        bookImageUrl: asStaticFileUrl('/images/b_zootopia_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_zootopia_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_zootopia_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-sugar2-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-10',
        course: 'gameDevelopment',
        bookName: 'Wreck-It-Ralph',
        bookImageUrl: asStaticFileUrl('/images/b_sugar2_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sugar2_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sugar2_character2_completed.png'),
      },
    ],
    'chapter-codeillusion-11': [
      {
        id: 'circle-codeillusion-advanced-frozen-media_art',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-11',
        course: 'mediaArt',
        bookName: 'Snow Magic',
        bookImageUrl: asStaticFileUrl('/images/b_frozen_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_frozen_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_frozen_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-sugar1-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-11',
        course: 'gameDevelopment',
        bookName: 'Dungeon Escape',
        bookImageUrl: asStaticFileUrl('/images/b_sugar1_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sugar1_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sugar1_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-bighero6-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-11',
        course: 'gameDevelopment',
        bookName: 'Breaking Tiles',
        bookImageUrl: asStaticFileUrl('/images/b_bighero6_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_bighero6_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_bighero6_character2_completed.png'),
      },
      {
        id: 'circle-codeillusion-advanced-sleepingbeauty-game_development',
        codeillusionPackageChapterDefinitionId: 'chapter-codeillusion-11',
        course: 'gameDevelopment',
        bookName: 'Dragon & Sword',
        bookImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_book_advanced.png'),
        characterImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_character2.png'),
        clearedCharacterImageUrl: asStaticFileUrl('/images/b_sleepingbeauty_character2_completed.png'),
      },
    ],
  }
}
