// Defined in Codex Master Data Sheet
// Refer: https://docs.google.com/spreadsheets/d/1hXUeCZgIUyx_liykNu6tlDJVwPu7MLKu_TIOoBwvdTo/edit#gid=500667118

import { Package } from '../../../../domain/entities/codex/Package'

export const packagesMapById: Record<string, Package> = {
  'codeillusion-package-basic-full-premium-heroic': {
    id: 'codeillusion-package-basic-full-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-full-premium-adventurous': {
    id: 'codeillusion-package-basic-full-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-full-standard': {
    id: 'codeillusion-package-basic-full-standard',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-premium-heroic': {
    id: 'codeillusion-package-basic-half-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-premium-adventurous': {
    id: 'codeillusion-package-basic-half-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-standard': {
    id: 'codeillusion-package-basic-half-standard',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-premium-heroic': {
    id: 'codeillusion-package-basic-1-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: '1 Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-premium-adventurous': {
    id: 'codeillusion-package-basic-1-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: '1 Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-standard': {
    id: 'codeillusion-package-basic-1-standard',
    packageCategoryId: 'codeillusion',
    name: '1 Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-premium-heroic': {
    id: 'codeillusion-package-basic-1_2-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: '1-2 Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-premium-adventurous': {
    id: 'codeillusion-package-basic-1_2-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: '1-2 Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-standard': {
    id: 'codeillusion-package-basic-1_2-standard',
    packageCategoryId: 'codeillusion',
    name: '1-2 Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-premium-heroic': {
    id: 'codeillusion-package-basic-1_3-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: '1-3 Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-premium-adventurous': {
    id: 'codeillusion-package-basic-1_3-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: '1-3 Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-standard': {
    id: 'codeillusion-package-basic-1_3-standard',
    packageCategoryId: 'codeillusion',
    name: '1-3 Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-premium-heroic': {
    id: 'codeillusion-package-basic-1_5-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: '1-5 Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-premium-adventurous': {
    id: 'codeillusion-package-basic-1_5-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: '1-5 Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-standard': {
    id: 'codeillusion-package-basic-1_5-standard',
    packageCategoryId: 'codeillusion',
    name: '1-5 Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-premium-heroic': {
    id: 'codeillusion-package-basic-1_6-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: '1-6 Premium (Hero)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-premium-adventurous': {
    id: 'codeillusion-package-basic-1_6-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: '1-6 Premium (Adventurous)',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-standard': {
    id: 'codeillusion-package-basic-1_6-standard',
    packageCategoryId: 'codeillusion',
    name: '1-6 Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-principal-standard': {
    id: 'codeillusion-package-basic-principal-standard',
    packageCategoryId: 'codeillusion',
    name: 'Principal - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-mediaArt-standard': {
    id: 'codeillusion-package-basic-mediaArt-standard',
    packageCategoryId: 'codeillusion',
    name: 'Media Art - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-webDesign-standard': {
    id: 'codeillusion-package-basic-webDesign-standard',
    packageCategoryId: 'codeillusion',
    name: 'Web Design - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-gameDevelopment-standard': {
    id: 'codeillusion-package-basic-gameDevelopment-standard',
    packageCategoryId: 'codeillusion',
    name: 'Game Development - Standard',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-premium-heroic': {
    id: 'codeillusion-package-advanced-full-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Premium (Hero)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-premium-adventurous': {
    id: 'codeillusion-package-advanced-full-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Premium (Adventurous)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-standard': {
    id: 'codeillusion-package-advanced-full-standard',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-premium-heroic': {
    id: 'codeillusion-package-advanced-half-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Premium (Hero)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-premium-adventurous': {
    id: 'codeillusion-package-advanced-half-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Premium (Adventurous)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-standard': {
    id: 'codeillusion-package-advanced-half-standard',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-mediaArt-standard': {
    id: 'codeillusion-package-advanced-mediaArt-standard',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Media Art - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-webDesign-standard': {
    id: 'codeillusion-package-advanced-webDesign-standard',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Web Design - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-gameDevelopment-standard': {
    id: 'codeillusion-package-advanced-gameDevelopment-standard',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Game Development - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-premium-heroic': {
    id: 'codeillusion-package-basic-and-advanced-full-premium-heroic',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Premium (Hero)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-premium-adventurous': {
    id: 'codeillusion-package-basic-and-advanced-full-premium-adventurous',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Premium (Adventurous)',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-standard': {
    id: 'codeillusion-package-basic-and-advanced-full-standard',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Standard',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-full-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-full-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-full-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-full-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-full-standard-no-principal': {
    id: 'codeillusion-package-basic-full-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Full Book - Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-half-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-half-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-half-standard-no-principal': {
    id: 'codeillusion-package-basic-half-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Half Book - Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-1-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1 Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-1-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1 Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1-standard-no-principal': {
    id: 'codeillusion-package-basic-1-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1 Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-1_2-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-2 Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-1_2-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-2 Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_2-standard-no-principal': {
    id: 'codeillusion-package-basic-1_2-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-2 Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-1_3-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-3 Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-1_3-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-3 Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_3-standard-no-principal': {
    id: 'codeillusion-package-basic-1_3-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-3 Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-1_5-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-5 Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-1_5-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-5 Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_5-standard-no-principal': {
    id: 'codeillusion-package-basic-1_5-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-5 Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-1_6-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-6 Premium (Hero) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-1_6-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-6 Premium (Adventurous) No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-1_6-standard-no-principal': {
    id: 'codeillusion-package-basic-1_6-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: '1-6 Standard No Principal',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-premium-heroic-no-principal': {
    id: 'codeillusion-package-advanced-full-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Premium (Hero) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-premium-adventurous-no-principal': {
    id: 'codeillusion-package-advanced-full-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Premium (Adventurous) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-full-standard-no-principal': {
    id: 'codeillusion-package-advanced-full-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Full Book - Standard No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-premium-heroic-no-principal': {
    id: 'codeillusion-package-advanced-half-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Premium (Hero) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-premium-adventurous-no-principal': {
    id: 'codeillusion-package-advanced-half-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Premium (Adventurous) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-advanced-half-standard-no-principal': {
    id: 'codeillusion-package-advanced-half-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Adv. Half Book - Standard No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-premium-heroic-no-principal': {
    id: 'codeillusion-package-basic-and-advanced-full-premium-heroic-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Premium (Hero) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-premium-adventurous-no-principal': {
    id: 'codeillusion-package-basic-and-advanced-full-premium-adventurous-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Premium (Adventurous) No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-and-advanced-full-standard-no-principal': {
    id: 'codeillusion-package-basic-and-advanced-full-standard-no-principal',
    packageCategoryId: 'codeillusion',
    name: 'Basic & Adv. Full Book - Standard No Principal',
    level: 'advanced',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-florida-film-academy-2023-01-camp': {
    id: 'codeillusion-package-florida-film-academy-2023-01-camp',
    packageCategoryId: 'codeillusion',
    name: 'Florida Film Academy Jan. 2023 Camp',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-freetrial-1_2_4book': {
    id: 'codeillusion-package-basic-freetrial-1_2_4book',
    packageCategoryId: 'codeillusion',
    name: 'DC ch1 + ch 2 & 4 book lessons',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-basic-freetrial-1_2_4book-pp': {
    id: 'codeillusion-package-basic-freetrial-1_2_4book-pp',
    packageCategoryId: 'codeillusion',
    name: 'DC ch1 + ch 2 & 4 book lessons + PP',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'cse-package-full-standard': {
    id: 'cse-package-full-standard',
    packageCategoryId: 'cse',
    name: 'Computer Science Essentials',
    level: 'basic',
    headerButtonLink: null,
    headerButtonText: null,
    redirectUrlWhenAllFinished: null,
  },
  'codeillusion-package-hour-of-code-2022-goofy-gems': {
    id: 'codeillusion-package-hour-of-code-2022-goofy-gems',
    packageCategoryId: 'codeillusion',
    name: 'Hour of Code 2022 ES/MS',
    level: 'basic',
    headerButtonLink: 'https://code.org/api/hour/finish',
    headerButtonText: "I'm Finished!",
    redirectUrlWhenAllFinished: 'https://code.org/api/hour/finish',
  },
  'codeillusion-package-hour-of-code-2022-goofy-books': {
    id: 'codeillusion-package-hour-of-code-2022-goofy-books',
    packageCategoryId: 'codeillusion',
    name: 'Hour of Code 2022 MS/HS',
    level: 'basic',
    headerButtonLink: 'https://code.org/api/hour/finish',
    headerButtonText: "I'm Finished!",
    redirectUrlWhenAllFinished: 'https://code.org/api/hour/finish',
  },
  'codeillusion-package-hour-of-code-2022-principal': {
    id: 'codeillusion-package-hour-of-code-2022-principal',
    packageCategoryId: 'codeillusion',
    name: 'Hour of Code 2022 K-2',
    level: 'basic',
    headerButtonLink: 'https://code.org/api/hour/finish',
    headerButtonText: "I'm Finished!",
    redirectUrlWhenAllFinished: 'https://code.org/api/hour/finish',
  },
}
