name: Trigger deploy to stg

on:
  push:
    branches: 'main'

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - run: |
          ret=$(curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GIT_SUBMODULE_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lifeistech/codex_usa_infrastructure/actions/workflows/deploy-only-codex-sourcecode-staging.yaml/dispatches \
            -d '{"ref":"main","inputs":{}}' \
            -s)
          echo "$ret"
          exit $(echo -n "$ret" | wc -l)
